language: c++
os: linux
sudo: false

matrix:
  include:
  
    - env: GCC_VERSION=5
      addons: &gcc49
        apt:
          packages:
            - gcc-5
            - g++-5
            - valgrind
            - libboost-all-dev
            - cmake
            - cmake-data
          sources:
            - ubuntu-toolchain-r-test

#install:
#  - cd ${TRAVIS_BUILD_DIR} && tools/deps
script:
  - cd ${TRAVIS_BUILD_DIR} && tools/test
after_success:
  - cd ${TRAVIS_BUILD_DIR} && tools/coverage
