sudo: required
language: cpp
dist: trusty

matrix:
  include:
  
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - valgrind
            - libboost-all-dev
      env: COMPILER=g++-5
      
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - valgrind
            - libboost-all-dev
      env: COMPILER=clang++-3.9
      
#install:
#  - cd ${TRAVIS_BUILD_DIR} && tools/deps
script:
  - cd ${TRAVIS_BUILD_DIR} && tools/test
after_success:
  - cd ${TRAVIS_BUILD_DIR} && tools/coverage
