dist: trusty
sudo: required
language: cpp

matrix:
  include:
    
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-all-dev
      env: UNIT_TESTS=true BOOST_VERSION=default
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

        
before_install:
    - eval "${MATRIX_EVAL}"
    
script:
  - cd ${TRAVIS_BUILD_DIR} && tools/test
  
after_success:
  - cd ${TRAVIS_BUILD_DIR} && tools/coverage
