sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - valgrind
            - libboost-all-dev
      env: COMPILER=g++-5
      
#install:
#  - cd ${TRAVIS_BUILD_DIR} && tools/deps
script:
  - cd ${TRAVIS_BUILD_DIR} && tools/test
after_success:
  - cd ${TRAVIS_BUILD_DIR} && tools/coverage
