#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

function set_travis_gcov {
  if [[ -n "${CLANG_VERSION:-}" ]]; then
    export GCOV="llvm-cov-${CLANG_VERSION}" ;
  elif [[ -n "${GCC_VERSION:-}" ]]; then
    export GCOV="gcov-${GCC_VERSION}" ;
  fi
}

# build project
set_travis_gcov
cd build
make coveralls
