#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

function prepare_build_dir {
  mkdir -p build
  cd build
  cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
}

prepare_build_dir
make all test
