#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

function prepare_build_dir {
  mkdir -p build

  # custom build cmake in path
  if [[ -e ${PWD}/cmake ]]; then
    export PATH=${PWD}/cmake/bin:${PATH}
  fi

  cd build
  cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
}

prepare_build_dir
make all test
